### ISSUE TITLE
First time user

### ISSUE THREAD

**Issue by El-Yazid** [harvard-edge/multilingual_kws#3]
Hello, 
i've read the article concerning the script, it seems great! 
But i'm facing problems using it for the first time, what are the files to make the embedding model ? how can i input the keywords to search for? 
any help would be welcomed

**Comment by mmaz** [comment]
Thanks - this code is still in a prerelease state unfortunately, but by July or August the repository will be organized and documented, and a pretrained embedding model will be released.

**Comment by rutsam** [comment]
Hello,

I wanted to know the plan to release the documentation still on course or it will be delayed

**Comment by mmaz** [comment]
Hi @rutsam we're still working on releasing our documentation and an end-to-end colab example, but there's a pretrained embedding model available as a prerelease in this repo, and an inference script + docker file which works with a finetuned model (see #4) produced by [`transfer_learning.transfer_learn`](https://github.com/harvard-edge/multilingual_kws/blob/1b13b65a9c8d677db11935738a960f9ea22c2405/embedding/transfer_learning.py#L14).

**Comment by mmaz** [comment]
Our introductory Colab tutorial is now available!
