### ISSUE TITLE
is there the inference.py？

### ISSUE THREAD

**Issue by huacilang** [harvard-edge/multilingual_kws#4]

**Comment by mmaz** [comment]
Hi, thanks for checking out our work! We are continuing to add documentation and will provide a full working example in colab soon, but there is an i[nference file here](https://github.com/harvard-edge/multilingual_kws/blob/main/embedding/run_inference.py) that works with a finetuned model. It's also designed to work with our [docker environment](https://github.com/harvard-edge/multilingual_kws/blob/main/docker/Dockerfile).
